import mongoose from 'mongoose';

const { Schema, model } = mongoose;

// ─── Sub-schemas ──────────────────────────────────────────────────────────────

const AttachmentSchema = new Schema(
  {
    url: { type: String, required: true },     // Cloudinary URL
    publicId: { type: String },
    type: {
      type: String,
      enum: ['image', 'video', 'audio', 'document', 'location'],
      default: 'image',
    },
    filename: { type: String, trim: true },
    size: { type: Number },                    // bytes
  },
  { _id: true }
);

const ReadReceiptSchema = new Schema(
  {
    user: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    readAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

const ReactionSchema = new Schema(
  {
    user: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    emoji: { type: String, required: true },   // e.g. "👍", "❤️", "🆘"
    reactedAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

// ─── Message Schema ───────────────────────────────────────────────────────────

const MessageSchema = new Schema(
  {
    // Who sent the message (null for system/AI messages)
    sender: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },

    // Message type determines the channel / audience
    messageType: {
      type: String,
      enum: [
        'direct',        // 1-on-1 private message
        'incident',      // Scoped to a specific incident thread
        'broadcast',     // Admin-to-all emergency broadcast
        'shelter',       // Scoped to a shelter
        'ai_response',   // AI-generated triage / guidance message
        'system',        // System notification (join, leave, status change)
      ],
      required: [true, 'Message type is required'],
    },

    // Content
    content: {
      type: String,
      trim: true,
      maxlength: [10000, 'Message content must not exceed 10 000 characters'],
    },

    // Media attachments (images, voice notes, documents)
    attachments: [AttachmentSchema],

    // Context references — set depending on messageType
    recipient: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      default: null,   // Populated for 'direct' messages
    },

    incident: {
      type: Schema.Types.ObjectId,
      ref: 'Incident',
      default: null,   // Populated for 'incident' messages
    },

    shelter: {
      type: Schema.Types.ObjectId,
      ref: 'Shelter',
      default: null,   // Populated for 'shelter' messages
    },

    // Read receipts for DMs / incident threads
    readBy: [ReadReceiptSchema],

    // Emoji reactions
    reactions: [ReactionSchema],

    // Threading — reply to another message
    replyTo: {
      type: Schema.Types.ObjectId,
      ref: 'Message',
      default: null,
    },

    // Whether this message was generated by AI
    isAiGenerated: {
      type: Boolean,
      default: false,
    },

    // For broadcast messages — target audience filter
    broadcastTarget: {
      roles: [{ type: String, enum: ['citizen', 'responder', 'admin', 'shelter_manager'] }],
      incidentTypes: [{ type: String }],
      region: { type: String, trim: true },
    },

    // Priority flag for emergency broadcasts
    priority: {
      type: String,
      enum: ['normal', 'high', 'critical'],
      default: 'normal',
    },

    // Soft delete
    isDeleted: {
      type: Boolean,
      default: false,
      select: false,
    },
    deletedAt: {
      type: Date,
      default: null,
      select: false,
    },

    // Edited flag
    isEdited: {
      type: Boolean,
      default: false,
    },
    editedAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// ─── Validation: content OR attachments required ──────────────────────────────

MessageSchema.pre('validate', function (next) {
  if (!this.content && (!this.attachments || this.attachments.length === 0)) {
    return next(new Error('A message must have either content or at least one attachment.'));
  }
  next();
});

// ─── Indexes ──────────────────────────────────────────────────────────────────

MessageSchema.index({ sender: 1, createdAt: -1 });
MessageSchema.index({ incident: 1, createdAt: 1 });
MessageSchema.index({ shelter: 1, createdAt: 1 });
MessageSchema.index({ recipient: 1, sender: 1, createdAt: -1 });
MessageSchema.index({ messageType: 1 });
MessageSchema.index({ priority: 1, messageType: 1 });

// ─── Virtual: Read count ──────────────────────────────────────────────────────

MessageSchema.virtual('readCount').get(function () {
  return this.readBy ? this.readBy.length : 0;
});

// ─── Virtual: Is broadcast ────────────────────────────────────────────────────

MessageSchema.virtual('isBroadcast').get(function () {
  return this.messageType === 'broadcast';
});

// ─── Static: Find conversation between two users ──────────────────────────────

MessageSchema.statics.findConversation = function (userA, userB, options = {}) {
  const { limit = 50, skip = 0 } = options;
  return this.find({
    messageType: 'direct',
    isDeleted: false,
    $or: [
      { sender: userA, recipient: userB },
      { sender: userB, recipient: userA },
    ],
  })
    .sort({ createdAt: -1 })
    .skip(skip)
    .limit(limit)
    .populate('sender', 'name avatar role')
    .populate('recipient', 'name avatar role');
};

// ─── Static: Find incident thread ─────────────────────────────────────────────

MessageSchema.statics.findIncidentThread = function (incidentId, options = {}) {
  const { limit = 100, skip = 0 } = options;
  return this.find({
    messageType: 'incident',
    incident: incidentId,
    isDeleted: false,
  })
    .sort({ createdAt: 1 })
    .skip(skip)
    .limit(limit)
    .populate('sender', 'name avatar role')
    .populate('replyTo', 'content sender');
};

export default model('Message', MessageSchema);
